--- 
- 
  blockinfile: 
    block: "     URIEncoding=\"UTF-8\"\n"
    insertbefore: connectionTimeout="20000"
    path: /usr/share/tomcat/conf/server.xml
    regexp: URIEncoding="UTF-8"
  name: "Setting Tomcat to UTF-8"
- 
  blockinfile: 
    block: |2
        
            <Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true"
                maxThreads="150" scheme="https" secure="true"
                clientAuth="false" sslProtocol="TLS"
                keystoreFile="/usr/share/tomcat/webapps/.keystore" keystorePass="Guac2019"
                URIEncoding="UTF-8" />"
    insertbefore: "Define an AJP 1.3"
    marker: "<!-- {mark} Adding port 8443 to Tomcat configs -->"
    path: /usr/share/tomcat/conf/server.xml
  name: "Adding port 8443 to Tomcat configs"
- 
  blockinfile: 
    block: |2
        
            <Valve className="org.apache.catalina.valves.RemoteIpValve"
                internalProxies="{{ ip }}"
                remoteIpHeader="x-forwarded-for"
                remoteIpProxiesHeader="x-forwarded-by"
                protocolHeader="x-forwarded-proto" />
            <Valve className="org.apache.catalina.valves.ErrorReportValve"
                showReport="false"
                showServerInfo="false"/>
    insertbefore: </Host>
    marker: "<!-- {mark} Preparing Tomcat for Reverse Proxies -->"
    path: /usr/share/tomcat/conf/server.xml
  name: "Preparing Tomcat for Reverse Proxies"
- 
  ignore_errors: true
  name: "Generating Java KeyStore Certs"
  shell: "keytool -genkey -alias {{ identifier }} -keyalg RSA -keysize 4096 -keystore /usr/share/tomcat/webapps/.keystore -storepass Guac2019 -keypass Guac2019 -noprompt -dname \"CN='', OU='', O='', L='', S='', C=''\"\n"
- 
  name: "Restarting and Enabling Tomcat"
  systemd: 
    enabled: true
    name: tomcat
    state: restarted
- 
  name: "Restarting and Enabling guacd"
  systemd: 
    enabled: true
    name: guacd
    state: restarted
- 
  name: "Adding SSL key from Vagrant Share"
  synchronize:
    src: /vagrant/ssl/guacamole.key
    dest: /etc/nginx/guacamole.key
- 
  name: "Adding SSL Cert from Vagrant Share"
  synchronize:
    src: /vagrant/ssl/guacamole.crt 
    dest: /etc/nginx/guacamole.crt  
- 
  blockinfile: 
    block: |
        server {
               listen 80;
               listen [::]:80;
               server_name {{ identifier }};
               return 301 https://$host$request_uri;
               location / {
                   proxy_pass http://{{ ip }}:8080/guacamole/;
               	   proxy_buffering off;
               	   proxy_http_version 1.1;
               	   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               	   proxy_set_header Upgrade $http_upgrade;
               	   proxy_set_header Connection $http_connection;
               	   proxy_cookie_path /guacamole/ /;
               	   access_log off;
               	   }
        }
    create: true
    path: /etc/nginx/conf.d/guacamole.conf
  name: "Setting up Gucamole Configuration"
- 
  blockinfile: 
    block: |
        server {
               listen 443 ssl http2 default_server;
               listen [::]:443 ssl http2 default_server;
               server_name {{ identifier }};
               server_tokens off;
               ssl_certificate guacamole.crt;
               ssl_certificate_key guacamole.key; 
               ssl_ciphers "TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384";
               ssl_protocols TLSv1.3 TLSv1.2;
               ssl_ecdh_curve secp521r1:secp384r1:prime256v1;
               ssl_prefer_server_ciphers on;
               ssl_session_cache shared:SSL:10m;
               ssl_session_timeout 1d;
               ssl_session_tickets off;
               add_header Referrer-Policy "no-referrer";
               add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
               add_header Content-Security-Policy "default-src 'none'; script-src 'self' 'unsafe-eval'; connect-src 'self'; object-src 'self'; frame-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self'; form-action 'self'; base-uri 'self'; frame-ancestors 'self';" always;
               add_header X-Frame-Options "SAMEORIGIN" always;
               add_header X-Content-Type-Options "nosniff" always;
               add_header X-XSS-Protection "1; mode=block" always;
               location / {
                   proxy_pass http://{{ ip }}:8080/guacamole/;
                   proxy_buffering off;
                   proxy_http_version 1.1;
                   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                   proxy_set_header Upgrade $http_upgrade;
                   proxy_set_header Connection $http_connection;
                   proxy_cookie_path /guacamole/ "/; HTTPOnly; Secure; SameSite";
                   access_log /var/log/nginx/guac_access.log;
                   error_log /var/log/nginx/guac_error.log;
                   }
        }
    create: true
    path: /etc/nginx/conf.d/guacamole_ssl.conf
  name: "Setting up Gucamole Configuration"
- 
  name: "Restarting and Enabling Nginx"
  systemd: 
    enabled: true
    name: nginx
    state: restarted
- 
  name: Adding Branding
  copy:
    src: /vagrant/jars/branding.jar
    dest: /var/lib/guacamole/extensions/branding.jar 
#- 
#  name: Adding extension
#  copy:
#    src: /vagrant/guacamole-auth-1.0.0.jar
#    dest: /var/lib/guacamole/extensions/guacamole-auth-1.0.0.jar 
- 
  get_url: 
    dest: /tmp/httpcomponents-client-5.0-bin.tar.gz
    url: "http://mirror.reverse.net/pub/apache//httpcomponents/httpclient/binary/httpcomponents-client-5.0-bin.tar.gz"
  name: "Downloading additional Jar Dependencies"
- 
  name: "Unpacking Dependencies"
  unarchive: 
    copy: false
    dest: /tmp
    src: /tmp/httpcomponents-client-5.0-bin.tar.gz
- 
  name: "Adding SSO Dependency extension"
  synchronize:
    src: /tmp/httpcomponents-client-5.0/lib/
    dest: /var/lib/guacamole/lib/
- 
  name: "Allow Jar File Permissions"
  sefcontext: 
    setype: tomcat_exec_t
    state: present
    target: "{{ item }}"
  with_items: 
    - /var/lib/guacamole/extensions/branding.jar
    - /var/lib/guacamole/extensions/guacamole-auth-jdbc-mysql-1.1.0.jar
- 
  command: "{{ item }}"
  name: "Configuring SELINUX"
  with_items: 
    - "restorecon -v /var/lib/guacamole/extensions/branding.jar"
#    - "restorecon -v /var/lib/guacamole/extensions/guacamole-auth-1.0.0.jar"
- 
  name: "Restarting Services"
  systemd: 
    enabled: true
    name: "{{ item }}"
    state: restarted
  with_items: 
    - guacd
    - tomcat
    - nginx

